version: "2"
services:
  zk:
    image: netflixoss/exhibitor:1.5.2
    networks: 
    - spark-network
  mesos_master:
    image: mesosphere/mesos-master:0.28.0-2.0.16.ubuntu1404
    environment:
      - MESOS_PORT=5050
      - MESOS_ZK=zk://zk:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    depends_on:
      - zk
    ports:
      - "5050:5050"
    networks: 
      - spark-network

  mesos_slave:
    image: xkd0413/mesos_slave
    privileged: true
    cpu_shares: 1
    mem_limit: 900000000
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://zk:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - /usr/local/bin/docker:/usr/local/bin/docker
      - ./pysparkFile:/pysparkFile
      - ./decisiontree:/decisiontree
      - ./target/scala-2.10:/app
    depends_on: 
      - mesos_master
    networks: 
      - spark-network
    entrypoint: ["mesos-slave", "--launcher=posix", '--resources=cpus(*):8; mem(*):15360;']

  kafka_master:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
      - zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka_master
      KAFKA_CREATE_TOPICS: "FIRST_TOPIC:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
    networks: 
      - spark-network
    depends_on:
      - zk
    volumes:
      - ./config:/config
    entrypoint: ["/opt/kafka_2.11-0.9.0.1/bin/kafka-server-start.sh", "/config/server.properties"]

networks:
  spark-network:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.0.10.0/24